# Einführung in das Programmieren mit Python
# Session 4-1: Data Handling

Jack Krüger, Sebastian Staab

SS 21

In this session we will use external packages for data handling.

## 4.1 Data Sources

In practice, there are many different **data sources** available where you can get data from. Each source has its own **advantages** and **disadvantages**. So far we have worked a lot with variables in our code, but they are not suitable for storing big amounts of data. That is why we also used files which can store more data, but they are difficult to exchange. This is where **application programming interface** (API) have emerged that provide an interface for exchanging data between clients and servers. At the same time, we will look at how to get data from **websites**. Behind APIs and websites, there is usually a **database system** in which all data is systematically stored and made available. These databases can also be used directly from Python. 

Below is a short (and probably incomplete) **list** of **data sources**. 

| Source | Description |
| -------- | ------- |
| Variable | reserved memory location to store data |
| File | physical storage to store data |
| Website | online available web resources |
| API | interface for exchanging data between clients and servers |
| Database | organized storage and access with software |

Today we will present the data pipeline using **simulated data** in **variables**. You will then complete the individual steps using a **file** by yourself. For this purpose we have a **dataset** on **flights** departing New York City in 2013. 

## 4.2 Data Handling

In our last exercise this morning, you have already seen how you can load the data of a file as a nested list with the use of the module `csv`. Maybe you have realized that this exercise is very **time-consuming** because many **little steps** must be implemented: How do I open the file? How do I iterate over the lines? How do I save it?

That is why developers have written an **external packages** for **data handling**. For example, in these packages files can be loaded in one line of code. Two of these packages are `pandas` and `numpy` and both support all kinds of different data sources. But let us take a look at both package one after the other. 

### Pandas

The **package** `pandas` helps you to arrange your **data** like **tables**. Through `pandas`, you can import, clean, transform, analyse and export data.

Let us first **import** the **package** or install it again if necessary. 

In [1]:
import pandas as pd

The primary component of `pandas` is its `DataFrame`. A `DateFrame` is organized like a **table** and has **rows** and **columns**. There are several ways to create a new `DataFrame`, but the easiest way to start is to take a **dictionary** and pass it into a new `DataFrame`.

Let us start with a **simple example** where we create a **table**.

In [2]:
# create dictionary
fruits = {"apple": [0.2, 1, 0.5, 1.2],
         "coconut": [3, 3.4, None, 4],
         "melon": [3, 3.5, 4, 4.5]}

# create dataframe
fruits = pd.DataFrame(fruits)

# print dataframe
fruits

apple  coconut  melon
0    0.2      3.0    3.0
1    1.0      3.4    3.5
2    0.5      NaN    4.0
3    1.2      4.0    4.5

Like you have just seen, `pandas` takes by default from the dictionary its **keys** as **columns** and its **values** as **cells**. Of course you can also pass the **row names** as a **separate attribute** to `DataFrame`. Assuming you want to change the **column** or **row names** afterwards, you can overwrite and access them with the **attributes** `columns` and `index`. 

Let us change the **column** and **row names** of our simple table.

In [5]:
# change column names
fruits.columns = ["Green Apple", "Indonesian Banana", "Watermelon"]

# change row names
fruits.index = ["Aldi", "Alnatura", "Penny", "Edeka"]

# print dataframe
fruits

Green Apple  Indonesian Banana  Watermelon
Aldi              0.2                3.0         3.0
Alnatura          1.0                3.4         3.5
Penny             0.5                NaN         4.0
Edeka             1.2                4.0         4.5

As your **datasets** become **larger** and non-trivial, you will not be able to print the entire data set anymore. `pandas` offers two methods `head()` and `tail()` to display either the **first** or the **last rows** of a `DataFrame`. By default, 5 rows are shown, but you can select any other number too. 

Let us print the **first** and **last row** once. 

In [6]:
# print first row
fruits.head(2)

Green Apple  Indonesian Banana  Watermelon
Aldi              0.2                3.0         3.0
Alnatura          1.0                3.4         3.5

In [7]:
# print last row
fruits.tail(2)

Green Apple  Indonesian Banana  Watermelon
Penny          0.5                NaN         4.0
Edeka          1.2                4.0         4.5

There are also several ways to change a `DataFrame` in `pandas`. A few ways are for example to **append** a `DataFrame` to another `DataFrame` with `append()`, find and delete **duplicate rows** with `drop_duplicates()`, and find rows with **missing values** and delete them with `dropna()`. Note that certain operations only pass a **reference** and others pass a **new** `DataFrame`. If you want to write to the exact same `DataFrame`, you can in most cases pass the argument `inplace = True` to the function. 

Let us try some **operations** on our data frame. 

In [16]:
# append dataframe to dataframe
fruits = fruits.append(fruits)

# print dataframe
fruits

Green Apple  Indonesian Banana  Watermelon
Aldi              0.2                3.0         3.0
Alnatura          1.0                3.4         3.5
Penny             0.5                NaN         4.0
Edeka             1.2                4.0         4.5
Aldi              0.2                3.0         3.0
Alnatura          1.0                3.4         3.5
Penny             0.5                NaN         4.0
Edeka             1.2                4.0         4.5

In [17]:
# drop duplicated in dataframe
fruits.drop_duplicates(inplace = True)

# print dataframe
fruits

Green Apple  Indonesian Banana  Watermelon
Aldi              0.2                3.0         3.0
Alnatura          1.0                3.4         3.5
Penny             0.5                NaN         4.0
Edeka             1.2                4.0         4.5

In [18]:
# drop rows with missing values
fruits.dropna(inplace = True)

# print dataframe
fruits

Green Apple  Indonesian Banana  Watermelon
Aldi              0.2                3.0         3.0
Alnatura          1.0                3.4         3.5
Edeka             1.2                4.0         4.5

Instead of **accessing** the entire `DateFrame`, you can also restrict the **selection** to certain columns, rows and cells. **Columns** can be easily restricted with an index with a **list** of their **names**. **Rows** can either be selected by their **name** using the **method** `loc[]` or by their **index** using the **method** `iloc[]`. Of course you can also restrict both columns and rows at the same time. 

Let us select **different parts** of our table.

In [19]:
# select column of melons
select = fruits[["Watermelon"]]

# print selected dataframe
print(select)

          Watermelon
Aldi             3.0
Alnatura         3.5
Edeka            4.5


In [20]:
# select row of Edeka
select = fruits.loc[["Edeka"]]

# print selected dataframe
print(select)

       Green Apple  Indonesian Banana  Watermelon
Edeka          1.2                4.0         4.5


In [21]:
# select column of melons and row of Edeka
select = fruits.loc[["Edeka"], ["Watermelon"]]

# print selected dataframe
print(select)

       Watermelon
Edeka         4.5


When you want to **select** parts of a `DataFrame` which fulfill a certain **condition**, then you can also write a **conditional statement** instead of a name or index. You then write the statement again as a kind of index behind the `DataFrame`. Then you get all parts of the `DateFrame` for which the condition is **correct**. Of course you can also **combine** several conditions in round brackets `(` `)` with logical ands `&` and logical ors `|`. 

Let us select **supermarkets** according to their **prices**. 

In [22]:
# create dictionary
fruits = {"apple": [0.2, 1, 0.5, 1.2],
         "coconut": [3, 3.4, None, 4],
         "melon": [3, 3.5, 4, 4.5]}

# create dataframe
fruits = pd.DataFrame(fruits)

# change column names
fruits.columns = ["Green Apple", "Indonesian Banana", "Watermelon"]


# change row names
fruits.index = ["Aldi", "Alnatura", "Penny", "Edeka"]

In [24]:
# select rows with melons cheaper than 4
select = fruits[fruits["Watermelon"] < 4]

# print selected dataframe
select

Green Apple  Indonesian Banana  Watermelon
Aldi              0.2                3.0         3.0
Alnatura          1.0                3.4         3.5

In [26]:
# select rows with melons cheaper than 4 or apple cheaper than 1
select = fruits[(fruits["Watermelon"] < 4) & (fruits["Green Apple"] < 1)]

# print selected dataframe
select


Green Apple  Indonesian Banana  Watermelon
Aldi          0.2                3.0         3.0

When you have finished your data wrangling, you can **save** the finished `DataFrame` obviously. In `pandas` you can save them as **CSV**, **JSON**, **SQL** with the **methods** `to_csv()`, `to_json()` and `to_sql()`. All in one line of code.

Let us **save** our **table** as **CSV** once. 

In [28]:
# save dataframe
fruits.to_csv("fruits.csv")

When you want to **load** your previous date or any other data, you can load it as `DataFrame` with `pandas` from a **CSV**, **JSON** or **SQL** with the **functions** `pd.read_csv()`, `pd.read_json()` or `pd.read_sql_query()`.

Let us **reload** the **data** from the **CSV**. 

In [29]:
# read dataframe
fruits = pd.read_csv("fruits.csv", index_col = 0)


# print dataframe
fruits

Green Apple  Indonesian Banana  Watermelon
Aldi              0.2                3.0         3.0
Alnatura          1.0                3.4         3.5
Penny             0.5                NaN         4.0
Edeka             1.2                4.0         4.5

In [48]:
fruits[["Green Apple", "Watermelon"]]

Green Apple  Watermelon
Aldi              0.2         3.0
Alnatura          1.0         3.5
Penny             0.5         4.0
Edeka             1.2         4.5

<div class="alert alert-block alert-info">
    <b>Exercise</b>: Import the <a href="https://raw.githubusercontent.com/snehavcs/NYC-Flight-Data-Analysis/master/flights.csv">flight dataset</a> as dataframe. Inspect the dataframe. Use the package pandas. 
</div>

In [30]:
flights = pd.read_csv("flights.csv", index_col = 0)
flights.head()

year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier tailnum  \
1  2013      1    1     517.0        2.0     830.0       11.0      UA  N14228   
2  2013      1    1     533.0        4.0     850.0       20.0      UA  N24211   
3  2013      1    1     542.0        2.0     923.0       33.0      AA  N619AA   
4  2013      1    1     544.0       -1.0    1004.0      -18.0      B6  N804JB   
5  2013      1    1     554.0       -6.0     812.0      -25.0      DL  N668DN   

   flight origin dest  air_time  distance  hour  minute  
1    1545    EWR  IAH     227.0      1400   5.0    17.0  
2    1714    LGA  IAH     227.0      1416   5.0    33.0  
3    1141    JFK  MIA     160.0      1089   5.0    42.0  
4     725    JFK  BQN     183.0      1576   5.0    44.0  
5     461    LGA  ATL     116.0       762   5.0    54.0

<div class="alert alert-block alert-info">
    <b>Exercise</b>: Add a column date in the dataframe with datetime objects using the columns year, month and day. 
</div>

In [31]:
flights["date"] = pd.to_datetime(flights[["year", "month", "day"]])
flights.head()

year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier tailnum  \
1  2013      1    1     517.0        2.0     830.0       11.0      UA  N14228   
2  2013      1    1     533.0        4.0     850.0       20.0      UA  N24211   
3  2013      1    1     542.0        2.0     923.0       33.0      AA  N619AA   
4  2013      1    1     544.0       -1.0    1004.0      -18.0      B6  N804JB   
5  2013      1    1     554.0       -6.0     812.0      -25.0      DL  N668DN   

   flight origin dest  air_time  distance  hour  minute       date  
1    1545    EWR  IAH     227.0      1400   5.0    17.0 2013-01-01  
2    1714    LGA  IAH     227.0      1416   5.0    33.0 2013-01-01  
3    1141    JFK  MIA     160.0      1089   5.0    42.0 2013-01-01  
4     725    JFK  BQN     183.0      1576   5.0    44.0 2013-01-01  
5     461    LGA  ATL     116.0       762   5.0    54.0 2013-01-01

In [33]:
import os

In [35]:
os.getcwd()

'C:\\Users\\Jack\\Python Course'

### Numpy

The **package** `numpy` provides Python with **multidimensional array objects**, which are easy and fast to work with. There are countless functions that make **scientific computing** convenient. We will only go through a few **simple use cases** with made up data. 

Let us first **import** the **package** or install it again if necessary. 

In [50]:
import numpy as np

There are several ways to create an array with `numpy`. The easiest way is to **create** an **array object** with the **function** `np.array()` and give it as input a **list** or **nested list**. But `numpy` offers many other helpful functions, like `np.zeros()` to create an **array** filled with **zeros** with a certain shape. Or you can create an array with **random values** with the help of the function `np.random.random()` and **reshape** it with the method `reshape()` to the desired shape. 

Note that **all elements** inside the array must have the **same data type**!

Let us create some **first arrays**.

In [53]:
# create array with values
fruits = np.array([[0.2,1,0.5,1.2],
                  [3,3.4,None,4],
                  [3,3.5,4,4.5]])


# print array
print(fruits)

[[0.2 1 0.5 1.2]
 [3 3.4 None 4]
 [3 3.5 4 4.5]]


In [54]:
# create array with zeros
zeros = np.zeros((3,4))

# print array
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [55]:
# create array with random numbers and reshape
random = np.random.random(12).reshape((3,4))


# print array
print(random)

[[0.20795272 0.15602477 0.45738354 0.610942  ]
 [0.76967616 0.0715506  0.1527543  0.54958516]
 [0.80346783 0.96739254 0.94433316 0.83867675]]


Besides the actual elements, each array has further information saved about itself in attributes. Thus, the **number** of **dimensions** of the array can be retrieved with the **attribute** `ndim`, the **total number** of **elements** with the **attribute** `size`, and the **size** of the **dimensions** with the **attribute** `shape`. 

Let us find out these **attributes** for our **array**. 

In [77]:
# create array with values
fruits = np.array([[0.2, 1, 0.5, 1.2], 
                   [3, 3.4, None, 4], 
                   [3, 3.5, 4, 4.5]])

# print dimensions
np.ndim(fruits)

2

In [57]:
# print number elements
np.size(fruits)

12

In [58]:
# print shape
np.shape(fruits)

(3, 4)

To access a **certain part** of an **array**, the array can be **indexed** and **sliced** by writing **square backets** `[` `]` behind the array. This procedure is similar to the one with lists. However, **multiple dimensions** can be **indexed** at once by indexing them in their order and separate them with commas `,`. With a two dimensional array you would first select an index of a row and then of a column. If an index is ommited, all following dimensions are displayed. With a two dimensional array only one index would show the entire row, along the second dimension. This sounds more complicated than it actually is, so let us try it out with a few examples. 

Let us access **certain parts** of our **array**. 

In [63]:
# select first row
select = fruits[0]

# print selected array
print(select)

[0.2 1 0.5 1.2]


In [64]:
# select first column
select = fruits[:,0]


# print selected array
print(select)

[0.2 3 3]


In [65]:
# select in last column first two elements
select = fruits[:2, -1]

# print selected array
print(select)

[1.2 4]


In [79]:
print(fruits)

[[0.2 1 0.5 1.2]
 [3 3.4 None 4]
 [3 3.5 4 4.5]]


As with `pandas`, we can **filter** the data in our **array** using **conditional statements**. You can also filter on **multiple dimensions** at the same time. 

In [78]:
# select columns where value in last row is smaller than 4
select = fruits[:,fruits[-1] < 4]

# print selected array
print(select)

[[0.2 1]
 [3 3.4]
 [3 3.5]]


In [67]:
# select columns where value in first row is smaller than 1 and last row is smaller than 4
select = fruits[:, (fruits[-1] < 4) & (fruits[0] < 1)]

# print selected array
print(select)

[[0.2]
 [3]
 [3]]


Finally we can show how to import and export data between `numpy` and `pandas`. To **export** an array as a `DataFrame` you can simply hand the array inside the **function** `pd.DataFrame()`. This will create a `DataFrame` without any row or column names, but you can add these as previously shown. To **import** the data from a `DataFrame` back into a `numpy` array, you can apply the **method** `to_numpy()` to your `DataFrame`. In the process of the import the column and row names are lost. 

Let us once **convert** the data between a **table** and an **array**. 

In [69]:
# import in dataframe
fruits = pd.DataFrame(fruits)

# change column names
fruits.columns = ["Aldi", "Alnatura", "Penny", "Edeka"]

# change row names
fruits.index = ["apple", "coconut", "melon"]

# print dataframe
fruits

Aldi Alnatura Penny Edeka
apple    0.2        1   0.5   1.2
coconut    3      3.4  None     4
melon      3      3.5     4   4.5

In [71]:
# create dictionary
fruits = {"apple": [0.2, 1, 0.5, 1.2],
          "coconut": [3, 3.4, None, 4],
          "melon": [3, 3.5, 4, 4.5]}

# create dataframe
fruits = pd.DataFrame(fruits)


# export as array
fruits = fruits.to_numpy()

# print array
fruits

array([[0.2, 3. , 3. ],
       [1. , 3.4, 3.5],
       [0.5, nan, 4. ],
       [1.2, 4. , 4.5]])

<div class="alert alert-block alert-info">
    <b>Exercise</b>: Change every odd number in the following 1 dimensional numpy array to 0. 
</div>

In [72]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [80]:
arr[arr%2==1] = 0

In [81]:
arr

array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10])

Original Source: 
Python Block Course; Prof. Dr. Karsten Donnay, Stefan Scholz; Winter Term 2019 / 2020